<?php
require_once __DIR__ . '/cors.php';
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/db.php';

$input        = json_decode(file_get_contents('php://input'), true);
$email        = isset($input['email'])        ? strtolower(trim($input['email']))  : '';
$verifyToken  = isset($input['verify_token']) ? trim($input['verify_token'])       : '';

if (empty($email) || !filter_var($email, FILTER_VALIDATE_EMAIL)) {
    http_response_code(400);
    echo json_encode(['success' => false, 'message' => 'Valid email required']);
    exit;
}

if (empty($verifyToken)) {
    http_response_code(400);
    echo json_encode(['success' => false, 'message' => 'verify_token required']);
    exit;
}

// ─── Identity-bound token check ───────────────────────────────────────────────
// The verify_token was generated by create-checkout.php and embedded in the
// Stripe success redirect URL.  Only a caller who completed payment for this
// specific email address will have seen that URL, so the token proves that the
// requester is the same party who initiated and completed the checkout flow.
//
// The token is one-time use: once consumed here it cannot be replayed.
// Comparison is done against the stored SHA-256 hash, not the raw token, so
// the plain-text value never needs to be persisted server-side.
try {
    $db = get_db();

    $db->exec("
        CREATE TABLE IF NOT EXISTS app_verify_tokens (
            id          INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
            email       VARCHAR(255) NOT NULL,
            token_hash  CHAR(64)     NOT NULL,
            expires_at  DATETIME     NOT NULL,
            used        TINYINT(1)   NOT NULL DEFAULT 0,
            created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_email_token (email, token_hash)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    ");

    $tokenHash = hash('sha256', $verifyToken);
    $stmt = $db->prepare(
        "SELECT id FROM app_verify_tokens
         WHERE email = ? AND token_hash = ? AND used = 0 AND expires_at > NOW()
         LIMIT 1"
    );
    $stmt->execute([$email, $tokenHash]);
    $tokenRow = $stmt->fetch();

    if (!$tokenRow) {
        http_response_code(403);
        echo json_encode(['success' => false, 'message' => 'Invalid or expired verification token']);
        exit;
    }

    // Consume the token — one-time use only.
    $db->prepare("UPDATE app_verify_tokens SET used = 1 WHERE id = ?")
       ->execute([$tokenRow['id']]);

} catch (PDOException $e) {
    http_response_code(500);
    echo json_encode(['success' => false, 'message' => 'Server error']);
    exit;
}

// --- Check local DB cache first ---
try {
    $db->exec("
        CREATE TABLE IF NOT EXISTS app_subscriptions (
            email       VARCHAR(255) NOT NULL UNIQUE,
            expires_at  DATETIME     NOT NULL,
            stripe_sub_id VARCHAR(255),
            created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    ");

    $stmt = $db->prepare("SELECT expires_at FROM app_subscriptions WHERE email = ?");
    $stmt->execute([$email]);
    $row = $stmt->fetch();

    if ($row && strtotime($row['expires_at']) > time()) {
        echo json_encode(['success' => true, 'subscribed' => true]);
        exit;
    }
} catch (PDOException $e) {
    // Non-fatal — fall through to Stripe check
}

// --- Live Stripe check ---
if (!defined('STRIPE_SECRET_KEY') || empty(STRIPE_SECRET_KEY)) {
    echo json_encode(['success' => true, 'subscribed' => false]);
    exit;
}

$ch = curl_init('https://api.stripe.com/v1/customers/search?query=' . urlencode("email:\"$email\"") . '&limit=1');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_USERPWD, STRIPE_SECRET_KEY . ':');
$response = curl_exec($ch);
curl_close($ch);

$customers = json_decode($response, true);
if (empty($customers['data'][0]['id'])) {
    echo json_encode(['success' => true, 'subscribed' => false]);
    exit;
}

$customerId = $customers['data'][0]['id'];

$ch = curl_init("https://api.stripe.com/v1/subscriptions?customer={$customerId}&status=active&limit=5");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_USERPWD, STRIPE_SECRET_KEY . ':');
$response = curl_exec($ch);
curl_close($ch);

$subs = json_decode($response, true);
$activeSub = null;
foreach ($subs['data'] ?? [] as $sub) {
    if ($sub['status'] === 'active') {
        $activeSub = $sub;
        break;
    }
}

if (!$activeSub) {
    echo json_encode(['success' => true, 'subscribed' => false]);
    exit;
}

// Cache in DB
try {
    $stmt = $db->prepare("
        INSERT INTO app_subscriptions (email, expires_at, stripe_sub_id)
        VALUES (?, FROM_UNIXTIME(?), ?)
        ON DUPLICATE KEY UPDATE expires_at = FROM_UNIXTIME(?), stripe_sub_id = ?, updated_at = NOW()
    ");
    $stmt->execute([
        $email,
        $activeSub['current_period_end'],
        $activeSub['id'],
        $activeSub['current_period_end'],
        $activeSub['id'],
    ]);
} catch (PDOException $e) {
    // Non-fatal
}

echo json_encode(['success' => true, 'subscribed' => true]);
