<?php
// Stripe redirects here after successful checkout.
// The verify_token in the URL was generated by create-checkout.php and is
// required to call check-subscription.php.  It proves the caller completed
// payment for the associated email address.
$token = isset($_GET['token']) ? trim($_GET['token']) : '';
$email = isset($_GET['email']) ? trim($_GET['email']) : '';
?><!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Subscribed! – NutriRank</title>
<style>
  body { font-family: -apple-system, sans-serif; background: #F5FAF5; color: #1B2B1B;
         display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; }
  .card { background: #fff; border-radius: 20px; padding: 40px 32px; text-align: center;
          box-shadow: 0 4px 24px rgba(0,0,0,.08); max-width: 420px; width: 90%; }
  .icon { font-size: 56px; margin-bottom: 16px; }
  h1 { color: #2D6A4F; font-size: 24px; margin: 0 0 10px; }
  p  { color: #6B8F6B; line-height: 1.6; margin: 0 0 24px; }
  .back { background: #2D6A4F; color: #fff; border: none; border-radius: 12px;
          padding: 14px 28px; font-size: 16px; cursor: pointer; text-decoration: none;
          display: inline-block; }
  .token-box { background: #F0F7F0; border: 1px solid #C8DFC8; border-radius: 10px;
               padding: 12px 16px; font-family: monospace; font-size: 13px;
               word-break: break-all; margin: 0 0 20px; color: #1B2B1B; text-align: left; }
  .token-label { font-size: 12px; color: #6B8F6B; margin: 0 0 8px; }
</style>
</head>
<body>
<div class="card">
  <div class="icon">🌿</div>
  <h1>You're subscribed!</h1>
  <p>Thank you for subscribing to NutriRank. Return to the app and tap <strong>Verify Subscription</strong> to unlock all nutrients.</p>

<?php if (!empty($token)): ?>
  <?php
    // Build a deep link so native apps can capture the token automatically.
    // The app should register the nutrirank:// scheme and read the token
    // from the query string on launch, then call check-subscription.php with
    // { "email": "...", "verify_token": "..." }.
    $deepLink = 'nutrirank://verify?token=' . urlencode($token)
              . (!empty($email) ? '&email=' . urlencode($email) : '');
  ?>
  <p style="font-size:13px;color:#6B8F6B;margin-bottom:8px;">
    If the app does not open automatically, copy your verification token below and paste it into the app.
  </p>
  <div class="token-label">Verification token</div>
  <div class="token-box"><?= htmlspecialchars($token, ENT_QUOTES, 'UTF-8') ?></div>
  <a class="back" href="<?= htmlspecialchars($deepLink, ENT_QUOTES, 'UTF-8') ?>">Return to NutriRank</a>
<?php else: ?>
  <a class="back" href="javascript:window.close()">Close &amp; return to app</a>
<?php endif; ?>
</div>
</body>
</html>
