import AsyncStorage from "@react-native-async-storage/async-storage";
import Constants from "expo-constants";
import React, { createContext, useContext, useEffect, useRef } from "react";
import { Platform } from "react-native";
import Purchases from "react-native-purchases";
import { useMutation, useQuery } from "@tanstack/react-query";

import { API_BASE } from "@/constants/api";

const REVENUECAT_TEST_API_KEY    = process.env.EXPO_PUBLIC_REVENUECAT_TEST_API_KEY;
const REVENUECAT_IOS_API_KEY     = process.env.EXPO_PUBLIC_REVENUECAT_IOS_API_KEY;
const REVENUECAT_ANDROID_API_KEY = process.env.EXPO_PUBLIC_REVENUECAT_ANDROID_API_KEY;

export const REVENUECAT_ENTITLEMENT_IDENTIFIER = "premium";

// AsyncStorage key for the server-issued device credential.
// This is a random 64-hex-char value generated by register-subscription.php.
// It is never derived from rc_app_user_id and is not visible in RevenueCat's dashboard,
// SDK logs, or proxied network traffic to api.revenuecat.com.
const CREDENTIAL_KEY = "nutrirank_credential";

const TOKEN_REFRESH_BUFFER_SECONDS = 60;

type TokenCache = { token: string; expiresAt: number } | null;

function getRevenueCatApiKey(): string {
  if (!REVENUECAT_TEST_API_KEY || !REVENUECAT_IOS_API_KEY || !REVENUECAT_ANDROID_API_KEY) {
    throw new Error("RevenueCat Public API Keys not found in environment");
  }
  if (__DEV__ || Platform.OS === "web" || Constants.executionEnvironment === "storeClient") {
    return REVENUECAT_TEST_API_KEY;
  }
  if (Platform.OS === "ios")     return REVENUECAT_IOS_API_KEY;
  if (Platform.OS === "android") return REVENUECAT_ANDROID_API_KEY;
  return REVENUECAT_TEST_API_KEY;
}

export function initializeRevenueCat() {
  const apiKey = getRevenueCatApiKey();
  Purchases.setLogLevel(Purchases.LOG_LEVEL.DEBUG);
  Purchases.configure({ apiKey });
  console.log("RevenueCat configured");
}

// Claims a server-generated device credential using a purchase-path transaction_id.
//
// HOW IT WORKS
// The RC SDK's purchasePackage() returns transaction.transactionIdentifier —- the App
// Store / Play Store identifier for the completed purchase.  That same identifier
// appears in the RC server-to-server webhook payload (event.transaction_id).
// register-subscription.php atomically consumes the matching webhook row and issues a
// credential.  An attacker who knows only rc_app_user_id cannot reproduce this value.
async function claimByTransactionId(transactionId: string): Promise<void> {
  const stored = await AsyncStorage.getItem(CREDENTIAL_KEY);
  if (stored) return; // Already have a credential — do not replace it.

  try {
    const res = await fetch(`${API_BASE}/register-subscription.php`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ transaction_id: transactionId }),
    });
    if (!res.ok) return;
    const data = await res.json();
    if (data.credential && typeof data.credential === "string") {
      await AsyncStorage.setItem(CREDENTIAL_KEY, data.credential);
    }
  } catch {
    // Non-fatal: the next premium search attempt returns 403 and surfaces a UI prompt.
  }
}

// Performs a nonce-bound restore flow and claims a credential from the resulting webhook.
//
// HOW IT WORKS
//  1. Request a server-generated 256-bit nonce from generate-restore-nonce.php.
//  2. Embed the nonce in the subscriber's RevenueCat profile via setAttributes().
//     Writing RC attributes requires running the SDK under the subscriber's own
//     app_user_id context — a third party who merely knows the subscriber's ID cannot
//     inject their nonce into the target account.
//  3. Call restorePurchases(), which causes RC to re-verify the App Store receipt and
//     fire a server-to-server webhook.  The webhook payload includes the subscriber's
//     current attributes (event.subscriber_attributes.restore_nonce.value).
//  4. rc-webhook.php reads the nonce from the trusted webhook payload and stores it
//     alongside transaction_id in rc_webhook_claims.
//  5. Wait briefly for the webhook to arrive, then call register-subscription.php with
//     { restore_nonce }.  The server claims the webhook row by nonce and issues a
//     credential.  If the webhook has not arrived yet, returns 202 and the client
//     retries once.
//
// WHY rc_app_user_id IS NOT SENT
//  register-subscription.php's restore path accepts ONLY restore_nonce — not
//  rc_app_user_id.  This means:
//   - Possessing rc_app_user_id alone cannot trigger credential issuance.
//   - The nonce in the webhook is trusted only because the subscriber's own device set
//     the attribute in RC before the restore.
async function claimByRestoreNonce(): Promise<void> {
  const stored = await AsyncStorage.getItem(CREDENTIAL_KEY);
  if (stored) return; // Already have a credential — do not replace it.

  try {
    // Step 1: Get a server-generated nonce.
    const nonceRes = await fetch(`${API_BASE}/generate-restore-nonce.php`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
    });
    if (!nonceRes.ok) return;
    const { nonce } = await nonceRes.json();
    if (!nonce || typeof nonce !== "string") return;

    // Step 2: Embed the nonce in the subscriber's RC attributes BEFORE restoring.
    // The RC SDK sends this with the restore request so the resulting webhook includes
    // it.  setAttributes is idempotent and overwrites any previous restore_nonce.
    await Purchases.setAttributes({ restore_nonce: nonce });

    // Step 3: Restore purchases (triggers RC server-side verification + webhook).
    await Purchases.restorePurchases();

    // Step 4: Give the RC webhook a few seconds to reach the server before claiming.
    await new Promise<void>((resolve) => setTimeout(resolve, 3000));

    // Step 5: Claim the credential using only the nonce (no rc_app_user_id sent).
    const claimRes = await fetch(`${API_BASE}/register-subscription.php`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ restore_nonce: nonce }),
    });

    if (claimRes.status === 202) {
      // Webhook not yet arrived — retry once after a further delay.
      await new Promise<void>((resolve) => setTimeout(resolve, 5000));
      const retryRes = await fetch(`${API_BASE}/register-subscription.php`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ restore_nonce: nonce }),
      });
      if (!retryRes.ok) return;
      const retryData = await retryRes.json();
      if (retryData.credential && typeof retryData.credential === "string") {
        await AsyncStorage.setItem(CREDENTIAL_KEY, retryData.credential);
      }
      return;
    }

    if (!claimRes.ok) return;
    const data = await claimRes.json();
    if (data.credential && typeof data.credential === "string") {
      await AsyncStorage.setItem(CREDENTIAL_KEY, data.credential);
    }
  } catch {
    // Non-fatal; user can tap the Restore button to try again.
  }
}

function useSubscriptionContext() {
  const customerInfoQuery = useQuery({
    queryKey: ["revenuecat", "customer-info"],
    queryFn: () => Purchases.getCustomerInfo(),
    staleTime: 60_000,
  });

  const offeringsQuery = useQuery({
    queryKey: ["revenuecat", "offerings"],
    queryFn: () => Purchases.getOfferings(),
    staleTime: 300_000,
  });

  // After a new purchase the SDK returns transaction.transactionIdentifier.
  // We send that to register-subscription.php so the server can match it against
  // the webhook it received from RevenueCat and issue a device credential.
  // rc_app_user_id is NOT sent to the server for credential issuance at any point.
  const purchaseMutation = useMutation({
    mutationFn: async (packageToPurchase: any) => {
      const result = await Purchases.purchasePackage(packageToPurchase);
      const transactionId: string | null =
        (result as any).transaction?.transactionIdentifier ?? null;
      return { customerInfo: result.customerInfo, transactionId };
    },
    onSuccess: async ({ transactionId }) => {
      customerInfoQuery.refetch();

      // iOS returns a usable StoreKit transactionIdentifier — claim by it.
      if (transactionId) {
        await claimByTransactionId(transactionId);
      }

      // Fallback for Android (transactionIdentifier is null there) or any case where
      // the purchase-path claim didn't land. claimByRestoreNonce is store-agnostic and
      // is skipped automatically if a credential already exists, so it's safe on iOS.
      const stored = await AsyncStorage.getItem(CREDENTIAL_KEY);
      if (!stored) {
        await claimByRestoreNonce();
      }
    },
  });

  // Restore flow: generate nonce → setAttributes → restorePurchases → claim by nonce.
  // No rc_app_user_id is sent to the credential-issuance endpoint.
  const restoreMutation = useMutation({
    mutationFn: async () => {
      await claimByRestoreNonce();
      return Purchases.getCustomerInfo();
    },
    onSuccess: () => {
      customerInfoQuery.refetch();
    },
  });

  const isSubscribed =
    customerInfoQuery.data?.entitlements.active?.[REVENUECAT_ENTITLEMENT_IDENTIFIER] !== undefined;

  const appUserID = customerInfoQuery.data?.originalAppUserId ?? null;

  // Auto-bootstrap for existing subscribers who do not yet have a stored credential
  // (e.g. upgraded from an older app version before this credential system was added).
  // Runs the full nonce-based restore flow silently in the background.
  useEffect(() => {
    if (!isSubscribed || !appUserID) return;

    AsyncStorage.getItem(CREDENTIAL_KEY).then((stored) => {
      if (!stored) {
        claimByRestoreNonce();
      }
    });
  }, [isSubscribed, appUserID]);

  const tokenCacheRef = useRef<TokenCache>(null);

  // Returns a valid 5-minute session token for premium API access.
  // Reads the device credential from AsyncStorage and exchanges it with
  // verify-entitlement.php for a fresh token.  rc_app_user_id is never forwarded.
  async function getEntitlementToken(): Promise<string | null> {
    const now    = Math.floor(Date.now() / 1000);
    const cached = tokenCacheRef.current;
    if (cached && cached.expiresAt - TOKEN_REFRESH_BUFFER_SECONDS > now) {
      return cached.token;
    }

    try {
      const credential = await AsyncStorage.getItem(CREDENTIAL_KEY);
      if (!credential) return null;

      const res = await fetch(`${API_BASE}/verify-entitlement.php`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ credential }),
      });
      if (!res.ok) return null;

      const data = await res.json();
      if (!data.token || !data.expires_in) return null;

      tokenCacheRef.current = {
        token:     data.token,
        expiresAt: now + data.expires_in,
      };
      return data.token;
    } catch {
      return null;
    }
  }

  return {
    customerInfo: customerInfoQuery.data,
    offerings:    offeringsQuery.data,
    isSubscribed,
    appUserID,
    isLoading:    customerInfoQuery.isLoading || offeringsQuery.isLoading,
    purchase:     purchaseMutation.mutateAsync,
    restore:      restoreMutation.mutateAsync,
    isPurchasing: purchaseMutation.isPending,
    isRestoring:  restoreMutation.isPending,
    getEntitlementToken,
  };
}

type SubscriptionContextValue = ReturnType<typeof useSubscriptionContext>;
const Context = createContext<SubscriptionContextValue | null>(null);

export function SubscriptionProvider({ children }: { children: React.ReactNode }) {
  const value = useSubscriptionContext();
  return <Context.Provider value={value}>{children}</Context.Provider>;
}

export function useSubscription() {
  const ctx = useContext(Context);
  if (!ctx) throw new Error("useSubscription must be used within a SubscriptionProvider");
  return ctx;
}
